CREATE TABLE IF NOT EXISTS t_user (
    id         INTEGER PRIMARY KEY,
    name       VARCHAR(32),
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    modifyTime DATETIME DEFAULT CURRENT_TIMESTAMP
);
