name: action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy with Maven
        run: ./mvnw deploy -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
